#!/usr/bin/env python3
"""Compile donor collision paths separately from target body animations."""
import json
import re
from customAnimation import ROOT, animation, sample
from customMoveTiming import animation_duration
from generateCustomAnimations import collision_frames, vec
from auditNormalMoves import arrays, enum_values, us_text

COLLISION_PILOTS = (('Kirby', 'AttackHi3', 'FTKirbyAnimUTilt', 'KirbyUTilt'),)


def frames_for(fighter, motion, name):
    tables = arrays(us_text((ROOT/'src/ft/ftdata.c').read_text()), 'FTMotionDesc')
    ids = enum_values((ROOT/'src/ft/ftdef.h').read_text(), 'FTCommonMotion')
    fields = [x.strip() for x in re.sub(r'[{}]', '', tables['dFT'+fighter+'MotionDescs']).split(',') if x.strip()]
    desc = fields[ids['nFTCommonMotion'+motion]*3:ids['nFTCommonMotion'+motion]*3+3]
    assert desc[0] == '&ll'+name+'FileID' and desc[2] == 'FTANIM_FLAG_NONE', (fighter, motion, desc)
    assert re.search(r'NULL,\s*/\* translate_scales \*/', next((ROOT/'src/relocData').glob('*_'+fighter+'Main.c')).read_text()), fighter
    duration = animation_duration(desc[0])
    frames = collision_frames(fighter, motion, sample(fighter, name, duration+1))
    assert frames[-1][0] == 0, 'Hitbox active after donor recovery'
    return frames


def main():
    output = ['/* Generated by tools/generateCustomCollisions.py. Do not edit. */']
    report = []
    for fighter, motion, name, label in COLLISION_PILOTS:
        frames = frames_for(fighter, motion, name)
        output.append('const FTCustomCollisionFrame sFTCustomCollision'+label+'[] = {')
        output.extend('    { { '+', '.join(vec(c) for c in centers)+' }, '+str(mask)+' },' for mask, centers in frames)
        output.append('};')
        report.append(dict(donor=fighter, motion=motion, animation=animation(name)[0].name,
                           frames=len(frames), active_frames=[i for i, (mask, _) in enumerate(frames) if mask],
                           bytes=len(frames)*52, bodies='all foreign original-roster bodies'))
    (ROOT/'src/ft/ftcustomcollisions.generated.inc').write_text('\n'.join(output)+'\n', encoding='utf-8')
    (ROOT/'build/collision-pilot-manifest.json').write_text(json.dumps(report, indent=2)+'\n', encoding='utf-8')
    print('Generated collision-only donor trajectories:', sum(r['bytes'] for r in report), 'bytes.')


if __name__ == '__main__':
    main()
