#!/usr/bin/env python3
"""Compile safe projectile-neutral timing and donor spawn geometry (US)."""
from functools import lru_cache
import re
from auditNormalMoves import ROOT, enum_values, calls
from customMoveCatalog import motion_descriptors, source_scripts
from customMoveTiming import animation_duration
from customAnimation import sample, rig, world, source_size, flag_word
from generateCustomMoves import expand
from generateCustomAnimations import vec

DONORS = ('Mario', 'Luigi', 'Pikachu', 'Ness')
JOINTS = (16, 16, 11, 0)


def commands(name, scripts=None):
    if scripts is None:scripts = source_scripts()
    names = tuple(scripts)
    result = []
    # Some native descriptor offsets point into the following adjacent array.
    # Resolve byte offsets against packed event lengths, including fallthrough.
    offset=re.fullmatch(r'(\w+)\s*\+\s*(0x[\da-fA-F]+|\d+)',name)
    if offset:
        name,skip=offset[1],int(offset[2],0)//4
        assert int(offset[2],0)%4==0
        while skip:
            total=sum(5 if 'MakeAttackColl' in op else
                      4 if op in ('ftMotionCommandEffect','ftMotionCommandEffectItemHold','ftMotionCommandSetDamageCollPartID') else
                      2 if op in ('ftMotionCommandGoto','ftMotionCommandSubroutine','ftMotionCommandSetParallelScript','ftMotionCommandSetAttackCollOffset','ftMotionCommandSetThrow') else 1
                      for op,_ in calls(scripts[name]))
            if skip<total:
                result.extend(expand(name+' + '+str(skip*4),scripts));break
            skip-=total
            name=names[names.index(name)+1]
        else:
            result.extend(expand(name,scripts))
        if any(op in ('ftMotionCommandEnd','ftMotionCommandReturn','ftMotionCommandGoto') for op,_ in calls(scripts[name])):
            return result
        name=names[names.index(name)+1]
    while True:
        result.extend(expand(name, scripts))
        # Mario/Luigi's grounded prefix falls directly into the next array.
        # These adjacent C arrays reconstruct a single native ROM stream.
        if any(op in ('ftMotionCommandEnd', 'ftMotionCommandReturn', 'ftMotionCommandGoto')
               for op, _ in calls(scripts[name])):
            return result
        following = names[names.index(name)+1]
        assert following.startswith(name.split('_')[0]+'_'), (name, following)
        name = following


@lru_cache(None)
def catalog():
    common = enum_values((ROOT/'src/ft/ftdef.h').read_text(), 'FTCommonMotion')
    result = []
    for fighter, joint in zip(DONORS, JOINTS):
        enum_fighter = 'Mario' if fighter == 'Luigi' else fighter
        path = ROOT/'src/ft/ftchar'/('ft'+enum_fighter.lower())/('ft'+enum_fighter.lower()+'.h')
        header = path.read_text().replace('nFTCommonMotionSpecialStart', str(common['nFTCommonMotionSpecialStart']))
        ids = enum_values(header, 'ft'+enum_fighter+'Motion')
        _, descriptors = motion_descriptors(fighter)
        for air in range(2):
            motion = ids['nFT'+enum_fighter+'MotionSpecial'+('AirN' if air else 'N')]
            desc = descriptors[motion]
            frame, shots = 0, []
            for op, args in commands(desc[1]):
                if op == 'ftMotionCommandWait': frame += int(args[0], 0)
                elif op == 'ftMotionCommandWaitAsync': frame = int(args[0], 0)
                elif op == 'ftMotionCommandSetFlag0' and int(args[0], 0) == 1: shots.append(frame)
            assert len(shots) == 1, (fighter, air, shots)
            firing = shots[0]
            duration = animation_duration(desc[0])
            assert 0 < firing < duration
            name, flags = desc[0][3:-6], flag_word(desc[2])
            if joint:
                bones, _ = rig(fighter, flags)
                pose = sample(fighter, name, firing+1, flags)[firing]
                local = world(bones, pose)[joint][1]
                size = source_size(fighter)
                # TopN's +/-90-degree facing rotation: local Z is forward.
                offset = (local[2]*size, local[1]*size, -local[0]*size)
            else:
                # Ness spawns from TopN + explicit world-space offsets.
                offset = (100, 180, 0)
            result.append(dict(fighter=fighter, air=air, firing=firing,
                               duration=duration, offset=offset, animation=name, flags=flags, joint=joint))
    return tuple(result)


def render():
    out = ['/* Generated by tools/generateNeutralProjectiles.py from US sources. */']
    for case in catalog():
        name = 'sFTCharBuilderProjectile'+case['fighter']+str(case['air'])
        out += ['static const ftMotionCommand '+name+'[] = {',
                '    ftMotionCommandWaitAsync('+str(case['firing'])+'),',
                '    ftMotionCommandSetFlag0(1), ftMotionCommandEnd()', '};']
    out += ['static const FTCustomMoveDefinition sFTCharBuilderProjectileMoves[4][2] = {']
    for index in range(4):
        records = []
        for case in catalog()[index*2:index*2+2]:
            name = 'sFTCharBuilderProjectile'+case['fighter']+str(case['air'])
            records.append('{ '+name+', ARRAY_COUNT('+name+'), '+str(case['duration'])+', 0 }')
        out.append('    { '+', '.join(records)+' },')
    out += ['};', 'static const Vec3f sFTCharBuilderProjectileOffsets[4][2] = {']
    for index in range(4):
        out.append('    { '+', '.join(vec(case['offset']) for case in catalog()[index*2:index*2+2])+' },')
    out += ['};', 'static const s32 sFTCharBuilderProjectileDonors[4] = { nFTKindMario, nFTKindLuigi, nFTKindPikachu, nFTKindNess };']
    return '\n'.join(out)+'\n'


if __name__ == '__main__':
    (ROOT/'src/ft/ftneutralprojectiles.generated.inc').write_text(render(), encoding='utf-8')
    for c in catalog():
        print(c['fighter'], 'air' if c['air'] else 'ground', 'fire', c['firing'], 'recovery', c['duration'], 'offset', c['offset'])
