#!/usr/bin/env python3
"""Source normal root travel and Ness's native bat-reflector socket."""
from functools import lru_cache
from customMoveCatalog import ROSTER, resolved_moves
from customAnimation import ROOT, sample, flag_word, source_size, rig, world, add, transform, TRANSN_FLAG
from generateCustomAnimations import vec

@lru_cache(None)
def catalog():
    rows=[]
    for fighter in ROSTER:
        row=[]
        for motion,desc,duration in resolved_moves(fighter):
            flags=flag_word(desc[2]); travel=(); socket=()
            if desc[1]!='dCustomEmpty' and ((flags & TRANSN_FLAG) or (fighter=='Ness' and motion.startswith('AttackS4'))):
                poses=sample(fighter,desc[0][3:-6],duration+1,flags)
                size=source_size(fighter)
                if flags & TRANSN_FLAG:
                    travel=tuple(((p.get(1,(0,)*10)[6]-poses[max(i-1,0)].get(1,(0,)*10)[6])*size,
                                  (p.get(1,(0,)*10)[5]-poses[max(i-1,0)].get(1,(0,)*10)[5])*size,
                                 -(p.get(1,(0,)*10)[4]-poses[max(i-1,0)].get(1,(0,)*10)[4])*size) for i,p in enumerate(poses))
                if fighter=='Ness' and motion.startswith('AttackS4'):
                    bones,_=rig(fighter,flags); points=[]
                    for pose in poses:
                        r,t=world(bones,pose)[0]
                        x,y,z=add(t,transform(r,(0,150,0)))
                        points.append((z*size,y*size,-x*size))
                    socket=tuple(points)
            row.append(dict(flags=flags,travel=travel,socket=socket,duration=duration,motion=motion))
        rows.append(tuple(row))
    return tuple(rows)

def render():
    out=['/* Generated by tools/generateNormalMechanics.py. */']
    seen={}
    def data(points,label):
        if not points:return 'NULL'
        if points not in seen:
            seen[points]=label
            out.append('const Vec3f '+label+'[] = {')
            out.extend('    '+vec(p)+',' for p in points);out.append('};')
        return seen[points]
    rows=[]
    for donor,row in enumerate(catalog()):
        entries=[]
        for index,c in enumerate(row):
            prefix='sFTCustomNormal'+str(donor)+'_'+str(index)
            entries.append('{ '+data(c['travel'],prefix+'Travel')+', '+data(c['socket'],prefix+'Socket')+', '+str(c['duration']+1)+', 0x'+format(c['flags'],'08x')+' }')
        rows.append('    { '+', '.join(entries)+' },')
    out+=['const FTCustomNormalMechanics sFTCustomNormalMechanics[12][33] = {',*rows,'};']
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    (ROOT/'src/ft/ftnormalmechanics.generated.inc').write_text(render(),encoding='utf-8',newline='\n')
    print('Generated donor normal movement and bat sockets for 396 entries.')
