#!/usr/bin/env python3
"""Compile grab shapes and numeric throw properties without donor states.

Grab timing follows the donor's catch animation. All source
capture anchors become the target body's own capture anchor. Throws omit
victim status IDs and keep the body's native release/cargo/suplex policy.
"""
import re
from generateCustomMoves import ROOT, ROSTER, arrays, us_text, enum_values, expand, semantic
from customMoveTiming import animation_duration

def main():
    scripts, throws = {}, {}
    for path in (ROOT/'src/relocData').glob('*MainMotion.c'):
        text = us_text(path.read_text())
        scripts.update(arrays(text,r'(?:ftMotionCommand|u32)'))
        throws.update(arrays(text,'FTThrowHitDesc'))
    scripts.update(arrays(us_text((ROOT/'src/relocData/201_FTCommonMoveset.c').read_text()),r'(?:ftMotionCommand|u32)'))
    ids = enum_values((ROOT/'src/ft/ftdef.h').read_text(),'FTCommonMotion')
    tables = arrays(us_text((ROOT/'src/ft/ftdata.c').read_text()),'FTMotionDesc')
    out = ['/* Generated by tools/generateCustomGrabs.py. */']
    timings, maps, refs, properties = [], [], [], []
    for fighter in ROSTER:
        fields = [x.strip() for x in re.sub(r'[{}]','',tables['dFT'+fighter+'MotionDescs']).split(',') if x.strip()]
        descs = [fields[i:i+3] for i in range(0,len(fields),3)]
        body = next((ROOT/'src/relocData').glob('*_'+fighter+'Main.c')).read_text()
        anchor = int(re.search(r'(\d+),\s*/\* joint_itemheavy_id',body)[1])
        maps.append(anchor)
        grab = descs[ids['nFTCommonMotionCatch']][1]
        frame, start, end, commands = 0, None, None, []
        for op,args in expand(grab,scripts):
            if op=='ftMotionCommandWaitAsync': frame=int(args[0],0)
            elif op=='ftMotionCommandWait': frame+=int(args[0],0)
            elif op in ('ftMotionCommandMakeAttackColl','ftMotionCommandMakeAttackCollScaled'):
                if start is None: start=frame
                assert frame==start,(fighter,'Grab needs phased support')
                nums=[int(value,0) for value in args]
                assert len(nums)==18 and 0<=nums[0]<4 and 0<=nums[1]<7
                nums[2]='nFTCustomJointGrabPoint' if nums[2]==anchor else 'nFTCustomJoint'+['Root','Torso','Head','HandL','HandR','ElbowL','ElbowR','KneeL','KneeR','FootL','FootR'][semantic(fighter,nums[2])]
                commands.append(op+'('+','.join(map(str,nums))+')')
            elif op=='ftMotionCommandClearAttackCollAll' and start is not None:
                end=frame
        assert start is not None and end is not None and end>start and 0<len(commands)<=4,fighter
        timings.append((start,end-start))
        name='sFTCustom'+fighter+'Grab'
        out += ['static const ftMotionCommand '+name+'[] = {', '    ftMotionCommandWaitAsync('+str(start)+'),']
        out += ['    '+command+',' for command in commands]
        out += ['    ftMotionCommandWait('+str(end-start)+'),', '    ftMotionCommandClearAttackCollAll(), ftMotionCommandEnd()', '};']
        refs.append('{ '+name+', ARRAY_COUNT('+name+'), '+str(animation_duration(descs[ids['nFTCommonMotionCatch']][0]))+', 0 }')
        row=[]
        for kind in ('Catch','ThrowF','ThrowB'):
            desc=descs[ids['nFTCommonMotion'+kind]]
            if kind=='ThrowF' and fighter=='Kirby':
                desc=next(d for d in descs if d[1]=='dKirbyMainMotion_ForwardThrow')
            if kind=='ThrowF' and fighter=='Donkey':
                desc=next(d for d in descs if d[1]=='dDonkeyMainMotion_CargoAirThrow_0x0D28')
            pointer=re.search(r'ftMotionCommandSetThrow\(\s*(?:\(u32\))?\s*(\w+)',scripts[desc[1]])
            assert pointer,(fighter,kind)
            source=throws.get(pointer[1],scripts.get(pointer[1],''))
            values=[int(value.strip(),0) for value in re.sub(r'[{}]','',source).split(',') if value.strip()]
            assert len(values)==14,(fighter,kind,values)
            numeric=[values[1:7],values[8:14]]
            for damage,angle,kbs,kbw,kbb,element in numeric:
                assert 0<=damage<=255 and -512<=angle<=511 and 0<=kbs<=1023 and 0<=kbw<=1023 and 0<=kbb<=1023 and 0<=element<=5
            row.append('{ '+', '.join('{ '+', '.join(map(str,part))+' }' for part in numeric)+' }')
        properties.append('{ '+', '.join(row)+' }')
    out += ['static const s8 sFTCustomGrabJointMap[12] = { '+', '.join(map(str,maps))+' };',
            'static const u16 sFTCustomGrabTimings[12][2] = { '+', '.join('{ '+str(a)+', '+str(b)+' }' for a,b in timings)+' };',
            'const FTCustomMoveDefinition sFTCustomGrabMoves[12] = { '+', '.join(refs)+' };',
            'static const FTCustomThrowDefinition sFTCustomThrowProperties[12][3][2] = {']
    out += ['    '+row+',' for row in properties]
    out += ['};']
    (ROOT/'src/ft/ftcustomgrabs.generated.inc').write_text('\n'.join(out)+'\n')
    print('Generated 12 grab shapes/windows and 36 two-part throw definitions; no donor victim status IDs.')

if __name__=='__main__': main()
