#!/usr/bin/env python3
"""Source phase durations for borrowed Up/Down B; no body animation timings."""
from functools import lru_cache
from auditNormalMoves import ROOT, ROSTER, enum_values, us_text
from customMoveCatalog import motion_descriptors
from customMoveTiming import animation_duration
from customAnimation import sample, rig, world, source_size, flag_word, transform, add
from generateCustomAnimations import vec
from generateNeutralProjectiles import commands

@lru_cache(None)
def catalog():
    common=enum_values((ROOT/'src/ft/ftdef.h').read_text(),'FTCommonMotion')
    result=[]
    for donor,fighter in enumerate(ROSTER):
        header=ROOT/'src/ft/ftchar'/('ft'+fighter.lower())/('ft'+fighter.lower()+'.h')
        ids=enum_values(header.read_text().replace('nFTCommonMotionSpecialStart',str(common['nFTCommonMotionSpecialStart'])),'ft'+fighter+'Motion')
        _,descs=motion_descriptors(fighter)
        for key,motion in ids.items():
            if 'MotionSpecial' not in key or not any(x in key for x in ('Hi','Lw')):continue
            desc=descs[motion]
            if not desc[0].startswith('&ll'):continue
            duration=animation_duration(desc[0])
            animation=next((ROOT/'src/relocData').glob('*_'+desc[0][3:-6]+'.c'))
            cycle='ftAnimLoop(' in us_text(animation.read_text())
            result.append((donor,motion,duration,cycle,key))
    return tuple(result)

@lru_cache(None)
def donkey_frames():
    row=next(row for row in catalog() if row[-1]=='nFTDonkeyMotionSpecialLwLoop')
    _,descs=motion_descriptors('Donkey');desc=descs[row[1]]
    poses=sample('Donkey',desc[0][3:-6],row[2]+1,flag_word(desc[2]))
    bones,_=rig('Donkey',flag_word(desc[2]));size=source_size('Donkey')
    events={};tick=0
    for op,args in commands(desc[1]):
        if op in ('ftMotionCommandWait','ftMotionCommandWaitAsync'):
            tick=int(args[0],0) if op.endswith('Async') else tick+int(args[0],0)
        elif 'AttackColl' in op:events.setdefault(tick,[]).append((op,[int(a,0) for a in args]))
    active={};frames=[]
    for frame,pose in enumerate(poses):
        for op,a in events.get(frame,()):
            if 'MakeAttackColl' in op:active[a[0]]=(a[2],tuple(a[7:10]))
            elif op=='ftMotionCommandClearAttackCollAll':active.clear()
        matrices=world(bones,pose);centers=[(0,0,0)]*4
        for aid,(joint,offset) in active.items():
            r,t=matrices[joint];centers[aid]=tuple(v*size for v in add(t,transform(r,offset)))
        frames.append((sum(1<<aid for aid in active),tuple(centers)))
    assert [i for i,(mask,_) in enumerate(frames) if mask]==[16,17,26,27]
    return tuple(frames)

def donkey_case():
    row=next(row for row in catalog() if row[-1]=='nFTDonkeyMotionSpecialLwLoop')
    _,descs=motion_descriptors('Donkey');desc=descs[row[1]]
    return dict(fighter='Donkey',phase='HandSlap',air=0,duration=row[2],
                animation=desc[0][3:-6],flags=flag_word(desc[2]),events=commands(desc[1]),
                frames=donkey_frames(),spawn=(),anchors=(),travel=())

def render():
    out=['/* Generated by tools/generateSpecialTiming.py. */',
         '/* Cycle is the donor animation loop, independent of the visible body. */',
         'static const FTCharBuilderSpecialTiming sFTCharBuilderSpecialTimings[] = {']
    out += ['    { '+str(donor)+', '+str(motion)+', { NULL, 0, '+str(duration)+', '+('4' if cycle else '0')+' } }, /* '+key+' */' for donor,motion,duration,cycle,key in catalog()]
    out+=['};','static const FTCustomCollisionFrame sFTCharBuilderDonkeyLwFrames[] = {']
    out+=['    { { '+', '.join(vec(v) for v in centers)+' }, '+str(mask)+' },' for mask,centers in donkey_frames()]
    out+=['};']
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    (ROOT/'src/ft/ftspecialtiming.generated.inc').write_text(render(),encoding='utf-8')
    print('Generated',len(catalog()),'donor phase durations and DK hit windows 16-17/26-27.')
