#!/usr/bin/env python3
"""Compile US normal collision timelines into local, semantic-joint data.

Collision operations, timing and common input/landing flag1 events survive.
No donor pointers, states, animation, effects, hurtbox changes or callbacks
enter the ROM table.
"""
from pathlib import Path
import re
from functools import lru_cache
from auditNormalMoves import ROOT, ROSTER, SLOTS, arrays, calls, enum_values, us_text
from customMoveTiming import animation_duration, landing_duration

# Root, torso, head, hands L/R, elbows L/R, knees L/R, shoes L/R.
# JointTree row ordinal + 4. Slope leg roots and item sockets establish sides.
MAPS = {
 'Mario': [0,5,12,10,16,9,15,20,25,22,27],
 'Fox': [0,5,12,10,16,9,15,20,25,22,27],
 'Donkey': [0,5,12,10,16,9,15,21,26,23,28],
 'Samus': [0,5,13,10,17,9,16,28,33,30,35],
 'Luigi': [0,5,12,10,16,9,15,20,25,22,27],
 'Link': [0,5,23,10,15,9,14,27,32,29,34],
 'Yoshi': [0,5,8,13,17,12,16,23,28,25,30],
 'Captain': [0,5,12,10,16,9,15,21,26,23,28],
 'Kirby': [0,5,6,11,16,10,15,22,27,24,29],
 'Pikachu': [0,5,11,10,18,9,17,21,26,23,28],
 'Purin': [0,5,6,11,15,10,14,21,26,23,28],
 'Ness': [0,5,12,10,16,9,15,20,26,22,28],
}
SEM = ['Root','Torso','Head','HandL','HandR','ElbowL','ElbowR','KneeL','KneeR','FootL','FootR']

@lru_cache(None)
def tree(name):
    text = next((ROOT/'src/relocData').glob('*_'+name+'Model.c')).read_text()
    body = re.search(r'DObjDesc\s+\w*JointTree\w*\[.*?\]\s*=\s*\{(.*?)\n\};',text,re.S)[1]
    rows = re.findall(r'\{\s*(\d+|0x[\da-fA-F]+),.*?\{\s*([^}]+)\}',body)
    parents, stack = {}, {}
    for i,(depth,_) in enumerate(rows):
        depth=int(depth,0)
        if depth == 18: break
        parents[i+4]=stack.get(depth-1,0)
        stack[depth]=i+4
    return parents

def semantic(name,joint):
    if joint in (0,1,2,3): return 0
    # Weapon sockets and accessories are attached to the holding hand. Tail
    # attacks use the torso on bodies without a tail; no foreign joint leaks.
    if name=='Link' and joint in (16,17,18,19): return 4
    if name=='Samus' and 18<=joint<=25: return 4
    if name=='Pikachu' and joint==12: return 2
    mapping=MAPS[name]
    parents=tree(name)
    assert joint in parents,(name,joint)
    # Exact location first, then nearest semantic ancestor. Shoulder/hip
    # pivots are explicitly associated with their limb rather than torso.
    for sem,raw in enumerate(mapping):
        if raw==joint: return sem
    for sem in (3,4,5,6,7,8,9,10,2):
        raw=mapping[sem]
        if parents.get(raw)==joint: return sem
    while joint:
        if joint in mapping: return mapping.index(joint)
        joint=parents.get(joint,0)
    return 1

def expand(name,scripts,ancestors=()):
    offset=re.fullmatch(r'(\w+)\s*\+\s*(0x[\da-fA-F]+|\d+)',name)
    skip=0
    if offset: name,skip=offset[1],int(offset[2],0)//4
    if name in ancestors: return [] # Cyclic rapid-jab paths are body-controlled.
    assert name in scripts,name
    commands=calls(scripts[name])
    if skip:
        cursor=0
        for i,(op,args) in enumerate(commands):
            if cursor==skip: commands=commands[i:];break
            cursor += (5 if 'MakeAttackColl' in op else 4 if op in ('ftMotionCommandEffect','ftMotionCommandEffectItemHold','ftMotionCommandSetDamageCollPartID') else 2 if op in ('ftMotionCommandGoto','ftMotionCommandSubroutine','ftMotionCommandSetParallelScript','ftMotionCommandSetAttackCollOffset','ftMotionCommandSetThrow') else 1)
        else: raise ValueError((name,skip))
    def block(i):
        out=[]
        while i<len(commands):
            op,args=commands[i];i+=1
            if op=='ftMotionCommandLoopEnd': return out,i
            if op=='ftMotionCommandLoopBegin':
                nested,i=block(i);out.extend(nested*int(args[0],0))
            elif op in ('ftMotionCommandSubroutine','ftMotionCommandGoto'):
                out.extend(expand(args[0],scripts,ancestors+(name,)))
                if op.endswith('Goto'): break
            elif op in ('ftMotionCommandEnd','ftMotionCommandReturn'): break
            else: out.append((op,args))
        return out,i
    return block(0)[0]

def main():
    from customMoveCatalog import source_scripts, MOTIONS, extra_ids, resolved_moves
    scripts=source_scripts();motions=MOTIONS
    out=['/* Generated by tools/generateCustomMoves.py. Do not edit. */',
         'static const s8 sFTCustomJointMaps[12][nFTCustomJointEnumCount] = {']
    out += ['    { '+', '.join(map(str,MAPS[n]))+' }, /* '+n+' */' for n in ROSTER]
    out+=['};']
    refs=[];maxwords=0;events=0;body_extra=[]
    for fighter in ROSTER:
        row=[]
        body_extra.append(extra_ids(fighter))
        for motion,desc,duration in resolved_moves(fighter):
            source_commands=[] if desc[1]=='dCustomEmpty' else expand(desc[1],scripts)
            gameplay_flag1 = motion in ('Attack11','Attack12','AttackLw3','Jab3','RapidStart','RapidLoop','RapidEnd') or motion.startswith('AttackAir')
            commands=[];words=0
            frame = 0
            for op,args in source_commands:
                if op in ('ftMotionCommandWait','ftMotionCommandWaitAsync'):
                    assert 0<=int(args[0],0)<=65535
                    value = int(args[0],0)
                    if motion == 'RapidLoop' and op == 'ftMotionCommandWaitAsync':
                        assert value >= frame, (fighter,motion,value,frame)
                        commands.append('ftMotionCommandWait('+str(value-frame)+')')
                        frame = value
                    else:
                        commands.append(op+'('+','.join(args)+')')
                        frame = value if op.endswith('Async') else frame+value
                    words+=1
                elif op == 'ftMotionCommandSetFlag1' and gameplay_flag1:
                    commands.append(op+'('+','.join(args)+')');words+=1
                elif 'AttackColl' in op:
                    nums=[int(x,0) for x in args]
                    if 'MakeAttackColl' in op:
                        assert len(nums)==18 and 0<=nums[0]<4 and 0<=nums[1]<7,(fighter,motion,nums)
                        nums[2]='nFTCustomJoint'+SEM[semantic(fighter,nums[2])]
                        words+=5
                    else:
                        assert op in ('ftMotionCommandClearAttackCollAll','ftMotionCommandClearAttackCollID','ftMotionCommandRefreshAttackCollID','ftMotionCommandSetAttackCollDamage','ftMotionCommandSetAttackCollSize','ftMotionCommandSetAttackCollSoundLevel','ftMotionCommandSetAttackCollOffset'),op
                        if nums: assert 0<=nums[0]<4
                        words+=2 if op.endswith('Offset') else 1
                    commands.append(op+'('+','.join(map(str,nums))+')');events+=1
            name='sFTCustom'+fighter+motion
            out+=['static const ftMotionCommand '+name+'[] = {']
            out+=['    '+c+',' for c in commands]
            if motion=='RapidLoop':
                # A timed local loop retains the donor period even when the
                # visible body's looping animation has a different length.
                assert duration >= frame,(fighter,motion,duration,frame)
                out+=['    ftMotionCommandWait('+str(duration-frame)+'), ftMotionCommandGotoS1(), 0,']
                words+=3
            out+=['    ftMotionCommandEnd()', '};']
            maxwords=max(maxwords,words+1)
            flags = (1 if gameplay_flag1 else 0) | (2 if motion == 'RapidLoop' else 0)
            row.append('{ '+name+', ARRAY_COUNT('+name+'), '+str(duration)+', '+str(flags)+' }')
        refs.append(row)
    out+=['const FTCustomMoveDefinition sFTCustomMoves[12]['+str(len(motions))+'] = {']
    out+=['    { '+', '.join(r)+' },' for r in refs]
    out+=['};','static const s32 sFTCustomMotionIDs[] = { '+', '.join('nFTCommonMotion'+m for m in motions[:29])+' };',
          'static const s32 sFTCustomBodyExtraMotionIDs[12][4] = {']
    out+=['    { '+', '.join(map(str,row))+' },' for row in body_extra]
    out+=['};',f'#define FTCUSTOMMOVE_SCRIPT_WORDS {maxwords}']
    (ROOT/'src/ft/ftcustommoves.generated.inc').write_text('\n'.join(out)+'\n')
    print(f'Generated {len(refs)*len(motions)} variants, {len(ROSTER)*len(SLOTS)} families; {events} collision events; max {maxwords} words.')

if __name__=='__main__': main()
