# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["0728", "0000"]
  character: ["0008", "3FFFC"]

definitions:
  base_character: MARIO
  series_logo_css: GAME_AND_WATCH
  select_pose: 1

shield_pose: ["008C", "3FFFC"]

files: [
  ["projectile_hitbox", "3FFFC", "0000"],
  "0x164",
  ["projectile_gfx", "0058", "3FFFC"],
  "0x0"
]

tag_team_preloads: [
  "projectile_hitbox"
]

name: "Mr. Game & Watch"

num_costumes: 7

charge_smash_frames:
  up: 6
  forward: 8
  down: 6

results:
  name: "Mr. G&W"
  name_scale: 0.8
  name_x: 25
  wins_x: 180

12cb:
  anim: "File.MRGAW_ANIM_DOWNSTANDU"

victory_theme:
  bend_range_overrides: [
    [19, 1200]
  ]

singleplayer:
  alt_name_width: 99

sounds:
  "057B": ANNOUNCER
  "057C": ATK_STRONG
  "057D": ATK_WEAK
  "057E": BEEP
  "057F": BIIP
  "0580": BOOP
  "0581": CHANT
  "0582": DMG
  "0583": TECH
  "0584": JUMP
  "0585": KO
  "0586": STAR_KO
  "0587": TAUNT
  "0588": UPB
  "0589": NEUTRALB
  "058A": DOWNB
  "058B": SLEEP

sounds_special:
  "0581":
    fgm_type: CHANT
    length: 280
  "058B":
    fgm_type: SLEEP
    length: "0x120"

cloaking_fix:
  fix_logic: GameAndWatch2D.CloakingFix.fix_
  parts:
    fish_bowl:
      hipoly:
        part_offset: "0x928"
        cmd_offsets: "0x28"
    flag:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0x28"
    blaster_one:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0xD0"
    blaster_two:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0xC8"
    torch:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0xE8"
    turtle:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0x28"
    fish_one:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: "0x28"
    bell:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    key:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    wind:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x110"
    chair:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    parachute:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    card_one:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_two:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_three:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_four:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_five:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_six:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_seven:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_eight:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    card_nine:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x130"
    fire_one:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    fire_two:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"
    fish_two:
      hipoly:
        part_offset: "0x958"
        cmd_offsets: "0x28"



announcer_fgm: "057B"

attributes:
  size_multi: 1.1
  dash_speed: 50.000
  dash_run_frames: 14.000
  death_fgm: "0585"
  star_ko_fgm: "0586"
  damaged_fgm: "0582"
  attack_sfx_1: "057C"
  attack_sfx_2: "057D"
  attack_sfx_3: "057E"
  heavy_lift_fgm: "057F"
  gravity: 2.450
  max_fall_speed: 45.000
  weight: 1.220
  shield_size: 310.000
