# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["01DC", "0000"]
  character: ["0004", "3FFFC"]

definitions:
  base_character: CAPTAIN
  variant_type: NA

name: "Spider-Man"

results:
  name: "Spider-Man"
  name_scale: 0.65
  name_x: 20
  wins_x: 185

singleplayer:
  stage1: "SPIRALM"
  stage2: "MADMM"
  stage3: "FROSTY"
  # Game will crash if it can't find a unique stage
  # (i.e. not used prior to character being rolled)
  # from the stage list during initial 1P setup
  alt_name_width: 71

  duo: # Duo support doesn't exist yet, adding parameters nonetheless
    anim: "0x617"
    moveset: "duo_moveset_captain"
    # flags: 0

  team:
    anim: "File.GND_TEAM_POSE"
    moveset: "0x80000000"
    # flags: 0

12cb:
  anim: "File.SPIDERMAN_ANIM_DOWNSTANDU"

# FROM: to
# Will switch all audio commands with id FROM to the generated ID for filename "to.aifc"
# So in your moveset commands replace any audio calls to these IDs
sounds:
  "FFF0": "ATK1" # FFFF
  "FFF1": "ATK2" # 057C
  "FFF2": "ATK3" # 057D
  "FFF3": "CAMERA" # 057E
  "FFF4": "CMON" # 057F
  "FFF5": "DEATH" # 0580
  "FFF6": "DMG1" # 0581
  "FFF7": "DMG2" # 0582
  "FFF8": "HEY" # 0583
  "FFF9": "ONEFORJJ" # 0584
  "FFFA": "SHOOT" # 0585
  "FFFB": "SHOWTIME" # 0586
  "FFFC": "TAUNT" # 0587
  "FFFD": "WEBBALL" # 0588
  "FFFE": "WEBSWING" # 0589
  "FFFF": "WEBTHROW" # 058A
  "FFE0": "ANNOUNCER" # 058B
  "FFE1": "SFX_NSP" # 058C
  "FFE2": "SFX_THREAD" # 058D
  "FFE3": "SFX_WEBTHROW" # 058E
  "FFE4": "SFX_NSP_HIT" # 058F

announcer_fgm: "FFE0"

attributes:
  death_fgm: "FFF5"
  damaged_fgm: "FFF6"
  star_ko_fgm: "FFF7"
  attack_sfx_1: "FFF0"
  attack_sfx_2: "FFF1"
  attack_sfx_3: "FFF2"

# If it's an array, the process will try to import a shield_pose.bin and use the offsets provided
# If it's just a string, it will use it as the shield pose file ID. In hex, works with or without "0x" at the start.
shield_pose: ["0064", "3FFFC"]

# Files 6, 7, 8, 9
# [Filename (without .bin), InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
# If it's a string, it will use that instead of adding a new file
files: [
  ["wb_hitbox", "3FFFC", "0000"],
  "0x15E",
  "0x14D",
  ["wb_gfx", "0058", "3FFFC"],
]

tag_team_preloads: [
  "wb_hitbox"
]