# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["01A8", "0000"]
  character: ["0008", "3FFFC"]

definitions:
  base_character: FOX
  series_logo_css: SONIC
  series_logo_model: SONIC
  select_pose: 4
  break_the_targets: SONIC
  board_the_platforms: SONIC

shield_pose: "0x013A"

name: "CBKnuckles"

num_costumes: 6

dpad_original: "MKnuckles"

charge_smash_frames:
  up: 3
  forward: 3
  down: 2

results:
  name: "Knuckles"
  name_scale: 0.75
  name_x: 25
  wins_x: 180

12cb:
  anim: "File.CBKNUCKLES_ANIM_DOWNSTAND_U"
  moveset: "defeated_moveset_sonic"

data_screen:
  name_x: 20
  name_y: 50

  use_existing_special_actions: 0
  use_existing_jab_actions: 1
  jab_char: MARIO

  # [Type, Action, Frames, Flags]
  actions:
    [
      ["USP", "CBKnuckles.Action.Spring", 666],
      ["NSP", "CBKnuckles.Action.GlideTurn", 666],
      ["NSP", "CBKnuckles.Action.GlideBegin", 60],
      ["NSP", "CBKnuckles.Action.GlideWait", 60],
      ["NSP", "CBKnuckles.Action.GlideEnd", 666],
      ["NSP", "CBKnuckles.Action.DiveAirBegin", 60],
      ["NSP", "CBKnuckles.Action.DiveAirLoop", 60],
      ["NSP", "CBKnuckles.Action.DiveLand", 666],
      ["DSP", "CBKnuckles.Action.SpinDashChargeGround", 60],
      ["DSP", "CBKnuckles.Action.SpinDashGround", 60],
      ["DSP", "CBKnuckles.Action.SpinDashEndGround", 666],
    ]

files:
  [
    ["spring_hitbox", "3FFFC", "0000"],
    "0x15A",
    "0x0A1",
    ["spring_gfx", "00A8", "3FFFC"],
  ]

tag_team_preloads: ["spring_hitbox"]

sounds:
  "04BE": CLIMB_CLING
  "053E": CHANT
  "0541": ANNOUNCER

sounds_special:
  "053E":
    fgm_type: CHANT
    length: 303

announcer_fgm: "0541"

attributes:
  death_fgm: "03E4"
  star_ko_fgm: "02B7"
  damaged_fgm: "02B7"

cloaking_fix:
  parts:
    head:
      hipoly:
        part_offset: "0x918"
        cmd_offsets: [
          "0x3A8",
          "0x4A8"
        ]
      lopoly:
        part_offset: "0x918"
        cmd_offsets: [
          "0x328",
          "0x420"
        ]
