# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["01A8", "0000"]
  character: ["0004", "3FFFC"]

definitions:
  base_character: YOSHI
  select_pose: 4
  break_the_targets: DRM #Dr. Mario
  board_the_platforms: GND #Ganondorf
  variant_type: NA

singleplayer:
  stage1: "SUBCON"
  stage2: "YOSHI_STORY_2"
  stage3: "TALTAL"
  # Game will crash if it can't find a unique stage
  # (i.e. not used prior to character being rolled)
  # from the stage list during initial 1P setup

  duo: # Duo support doesn't exist yet, adding parameters nonetheless
    anim: "0x1C8"
    moveset: "duo_moveset_yoshi"
    # flags: 0

  team:
    anim: "0x745"
    moveset: "team_moveset_yoshi"
    # flags: 0

num_costumes: 9

yoshi_jump: True
yoshi_shield: True
yoshi_grab: True
yoshi_recover: True
# yoshi_upspecial: True
yoshi_downspecial: True

# Files 6, 7, 8, 9
# [Filename (without .bin), InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
files: [
  [
  ["nsp_hitbox", "3FFFC", "0000"],
  ["usp_hitbox", "3FFFC", "0000"],
  ["nspfire_hitbox", "3FFFC", "0000"],
  ],
  "0x0",
  "0x0",
  "0x0",
]

# Files that are imported in the reqlist of other files
# a lot of times these are GFX used for projectiles ("hitbox" file)
append_files: [
  ["nsp_gfx", "0058", "3FFFC"],
  ["usp_gfx", "0058", "3FFFC"],
  ["nspfire_gfx", "0058", "3FFFC"],
]

tag_team_preloads: ["merged_file_0"]

charge_smash_frames:
  up: 5
  forward: 9
  down: 6

results:
  name: "Birdo"
  name_scale: 1
  name_x: 30
  wins_x: 170

sounds:
  "FFF0": BirdoAttack1
  "FFF1": BirdoAttack2
  "FFF2": BirdoJump2
  "FFF3": BirdoHurt
  "FFF4": BirdoDeath
  "FFF5": BirdoSky
  "FFF6": BirdoANnouncer
  "FFE0": BirdoKiss
  "FFE1": BirdoYeah
  "FFE2": BirdoAllRight
  "FFE3": BirdoYahoo
  "FFE4": BirdoFine
  "FFE5": BirdoTennisCharge
  "FFE6": BirdoTennisHit
  "FFE7": BirdoFlutter
  "FFE8": BirdoSmash1
  "FFE9": BirdoSmash2
  "FFEA": BirdoJump1
  "FFEB": BirdoSleepyDizzy
  "FFEC": BirdoShoot
  "FFED": BirdoTeeter
  "FFEE": Chant
  "FFEF": BirdoGrab

announcer_fgm: "FFF6"

sounds_special:
  "FFEE":
    fgm_type: CHANT
    length: 280
  "FFEB":
    fgm_type: SLEEP
    length: "0x120"

attributes:
  death_fgm: "FFF4"
  star_ko_fgm: "FFF5"
  damaged_fgm: "FFF3"
  attack_sfx_1: "FFF0"
  attack_sfx_2: "FFF1"
  attack_sfx_3: "FFF2"
  heavy_lift_fgm: "FFED"

cloaking_fix:
  fix_logic: Birdo.CloakingFix.fix_
  parts:
    racket:
      hipoly:
        part_offset: "0x930"
        cmd_offsets: "0xB8"
      lopoly:
        part_offset: "0x930"
        cmd_offsets: "0xB8"
    ball:
      hipoly:
        part_offset: "0x964"
        cmd_offsets: "0x70"
      lopoly:
        part_offset: "0x964"
        cmd_offsets: "0x70"