# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
name: "Training Stage"

offsets:
  header: ["0098", "0014"]
  stage: ["4DFC", "3FFFC"]
  background: ["269D0", "3FFFC"]

mushroom_kingdom_camera: true

music:
  main: KH2FM_CAVERN_OF_REMEMBRANCE
  occasional: FORGONE
  rare: CORRIDORS_OF_TIME
  rare2: BLUE_RESORT


spawn_locations:
  default:
    p1: [-1000,0]
    p2: [1000,0]
    p3: [-2500,0]
    p4: [2500,0]
  neutral:
    p1: [-1000,0]
    p2: [1000,0]
    p3: [-2500,0]
    p4: [2500,0]
