# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
name: "Waffle House"

offsets:
  header: ["0098", "0014"]
  stage: ["276C", "3FFFC"]
  background: ["269D0", "3FFFC"]

mushroom_kingdom_camera: true

music:
  main: STREETFIGHTER2_RYU_THEME
  occasional: STREETFIGHTER2_KEN_THEME
  rare: MORTALKOMBAT_TECHNO_SYNDROME
  rare2: -1

series_position:
  x: 4.25
  y: 19

spawn_locations:
  default:
    p1: [-2000,1011]
    p2: [2000,1011]
    p3: [-1000,1011]
    p4: [1000,1011]
  neutral:
    p1: [-2000,1011]
    p2: [2000,1011]
    p3: [-1000,1011]
    p4: [1000,1011]