# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
name: "Halberd"

series: KIRBY

training_background: YOSHIS_ISLAND

offsets:
  header: ["0098", "0014"]
  stage: ["3CA4", "3FFFC"]
  background: ["269D0", "3FFFC"]

mushroom_kingdom_camera: true

magnifying_glass_color: "#F62C04" # Either HTML color or [R, G, B]

music:
  main: MK_REVENGE
  occasional: KIRBY_64_BOSS
  rare: BATTLE_AMONG_FRIENDS
  rare2: VS_MARX

series_position:
  x: 4.25
  y: 19

spawn_locations:
  default:
    p1: [-2100, 230]
    p2: [2100, 230]
    p3: [700, 0]
    p4: [-700, 0]
  neutral:
    p1: [-2100, 230]
    p2: [2100, 230]
    p3: [700, 0]
    p4: [-700, 0]