# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
name: "Training Stage DL"

offsets:
  header: ["0098", "0014"]
  stage: ["653C", "3FFFC"]
  background: ["269D0", "3FFFC"]

mushroom_kingdom_camera: true

music:
  main: KH2FM_CAVERN_OF_REMEMBRANCE
  occasional: FORGONE
  rare: CORRIDORS_OF_TIME
  rare2: BLUE_RESORT


spawn_locations:
  default:
    p1: [-1400,910]
    p2: [1400,910]
    p3: [-0,1550]
    p4: [0,5]
  neutral:
    p1: [-1400,910]
    p2: [1400,910]
    p3: [-0,1550]
    p4: [0,5]
