# [InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
offsets:
  main: ["02A8", "0000"]
  character: ["0004", "3FFFC"]

definitions:
  base_character: FOX
  series_logo_css: ZELDA
  series_logo_model: ZELDA
  select_pose: 4
  break_the_targets: YL #Young Link
  board_the_platforms: YL #Young Link
  variant_type: NA

singleplayer:
  stage1: "HTEMPLE"
  stage2: "GREAT_BAY"
  stage3: "TALTAL"
  # Game will crash if it can't find a unique stage
  # (i.e. not used prior to character being rolled)
  # from the stage list during initial 1P setup
  alt_name_width: 76

  duo: # Duo support doesn't exist yet, adding parameters nonetheless
    anim: "0x170"
    moveset: "duo_moveset_mario"
    # flags: 0

  team:
    anim: "File.PEACH_TEAM_POSE"
    moveset: "team_moveset"
    # flags: 0

shield_pose: ["009C", "3FFFC"]

name: "Young Zelda"
num_costumes: 9

results:
  name: "Young Zelda"
  name_scale: 0.55
  name_x: 20
  wins_x: 180

charge_smash_frames:
  up: 3
  forward: 7
  down: 6

12cb:
  anim: "File.PEACH_DOWN_STAND_U"

victory_theme:
  master_volume_override: 127

# Files 6, 7, 8, 9
# [Filename (without .bin), InternalFileTableOffsetBytes, InternalFileResourceOffsetBytes]
files: [
  ["nsp_hitbox", "3FFFC", "0000"],
  "0x15A",
  "0x0A1",
  ["nsp_gfx", "0058", "3FFFC"],
]

sounds:
  "FFE0": YZeldaNoteA
  "FFE1": YZeldaNoteDown
  "FFE2": YZeldaNoteRight
  "FFE3": YZeldaNoteLeft
  "FFE4": YZeldaNoteUp
  "FFE5": YZeldaWin2
  "FFE6": SFX_NSP_HIT_FULL
  "FFE7": NSP_BOW_PULL
  "FFE8": NSP_BOW_FAIL
  "FFE9": NSP_BOW_SHOOT
  "FFEA": NSP_BOW_FULL
  "FFEB": YZeldaWin3Start
  "FFEC": YZeldaWin3End
  "FFED": USP_TELE
  "FFEE": YZeldaUSP1
  "FFEF": YZeldaUSP2
  "FFF0": YZeldaDamage
  "FFF1": YZeldaDizzy
  "FFF2": YZeldaHuh
  "FFF3": YZeldaLaugh
  "FFF4": YZeldaLightGasp
  "FFF5": YZeldaSky
  "FFF6": YZeldaSleep
  "FFF7": YZeldaDeath
  "FFF8": USP_TELE_START
  "FFF9": YoungZeldaAnnouncer

announcer_fgm: "FFF9"

attributes:
  death_fgm: "FFF7"
  star_ko_fgm: "FFF5"
  damaged_fgm: "FFF0"
  attack_sfx_1: "FFF2"
  attack_sfx_2: "FFF6"
  attack_sfx_3: "FFF2"
  heavy_lift_fgm: "FFF1"

# sword trail definitions
sword_trails:
  # yzelda_left_trail
  "F1":
    part: "0x6"
    axis: "AXIS_Z"
    color1: "0x40C0FF00"
    color2: "0x80E0FF00"
    start_pos: -10
    end_pos: 30

  # yzelda_right_trail
  "F2":
    part: "0xd"
    axis: "AXIS_Z"
    color1: "0x40C0FF00"
    color2: "0x80E0FF00"
    start_pos: -10
    end_pos: 30

  # yzelda_left_alt_trail
  "F3":
    part: "0x6"
    axis: "AXIS_Y"
    color1: "0x40C0FF00"
    color2: "0x80E0FF00"
    start_pos: -10
    end_pos: 30

cloaking_fix:
  fix_logic: YZelda.CloakingFix.fix_
  parts:
    arrow:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: ["0x170"]
      lopoly:
        part_offset: "0x92C"
        cmd_offsets: ["0x170"]
    arrow_light:
      hipoly:
        part_offset: "0x92C"
        cmd_offsets: ["0x170"]
      lopoly:
        part_offset: "0x92C"
        cmd_offsets: ["0x170"]